# Generated by Django 3.2.11 on 2022-02-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ECR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EqCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Facilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GpoElectr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gpo_elect', models.CharField(max_length=80)),
                ('marca_gpo_elect', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo_gpo_elect', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_combustible_gpo_elect', models.CharField(blank=True, max_length=80, null=True)),
                ('cap_combustible_gpo_elect', models.PositiveIntegerField(blank=True, null=True)),
                ('cant_combustible_gpo_elect', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehiculo', models.CharField(max_length=80)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=80, null=True)),
                ('cap_combustible_vehiculo', models.PositiveIntegerField(blank=True, null=True)),
                ('cant_combustible_vehiculo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sub_tipo', models.CharField(max_length=50)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='ecr.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('indicador', models.FloatField()),
                ('facilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='ecr.facilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('facilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ecr.facilidad')),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_por_subtipos', to='ecr.subtipoevento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_por_tipos', to='ecr.tipoevento')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAlistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('S', 'En servicio'), ('L', 'Limitado'), ('F', 'F/S')], max_length=1)),
                ('facilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_alistamiento', to='ecr.facilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('Eq_com', 'Vehiculo', 'Gpo_electr')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('facilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='ecr.facilidad')),
            ],
        ),
    ]
