# Generated by Django 3.2.11 on 2022-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0002_alter_estadoalistamiento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoalistamiento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estadoalistamiento',
            name='status',
            field=models.CharField(choices=[('S', 'En servicio'), ('L', 'Limitado'), ('F', 'F/S')], max_length=1),
        ),
    ]
