# Generated by Django 3.2.11 on 2022-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0003_auto_20220217_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifradoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenDestinoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrecedenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipe', models.CharField(max_length=50)),
            ],
        ),
    ]
