# Generated by Django 3.2.11 on 2022-11-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0004_cifradoevento_clasificacionevento_origendestinoevento_precedenciaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cifrado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecr.cifradoevento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='clasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecr.clasificacionevento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='origen_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecr.origendestinoevento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='precedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecr.precedenciaevento'),
            preserve_default=False,
        ),
    ]
