# Generated by Django 3.2.11 on 2022-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='grado',
            field=models.CharField(blank=True, choices=[('1', 'Cabo'), ('2', 'Cabo 1ro'), ('3', 'Sargento')], max_length=1, null=True),
        ),
    ]
